version: "3.5"

services:
  db:
    image: postgres:12
    networks:
      - sonarnet
    environment:
      - TZ=Europe/Bratislava
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /var/sonar_home/postgres:/var/lib/postgresql
      - /var/sonar_home/postgres/data:/var/lib/postgresql/data
    configs:
      - uid: '1001'
        gid: '1001'

  sonarqube:
    image: sonarqube:8-community
    expose:
      - 90
    ports:
      - 90:9000
    networks:
      - sonarnet
    environment:
      - TZ=Europe/Bratislava
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - /var/sonar_home/conf:/opt/sonarqube/conf
      - /var/sonar_home/data:/opt/sonarqube/data
      - /var/sonar_home/extensions:/opt/sonarqube/extensions
      - /var/sonar_home/logs:/opt/sonarqube/logs
    configs:
      - uid: '1001'
        gid: '1001'
    # XXX Upgrade pluginov
    # https://docs.sonarqube.org/latest/instance-administration/marketplace/
    # https://docs.sonarqube.org/latest/instance-administration/plugin-version-matrix/

  jenkins:
    #image: jenkins:jenkins:lts
    build:
      context: ./jenkins
    expose:
      - 81
    ports:
      - "81:8080"
    network_mode: bridge
    environment:
      - TZ=Europe/Bratislava
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - uid: '1000'
        gid: '1000'

networks:
  sonarnet:

